### ISSUE TITLE
NatsStreamingAction Subject Duplication When passing NatsMessage object

### ISSUE THREAD

**Issue by DSwift510** [Logimethods/nats-connector-gatling#4]
Hi, 

I've been using the nats-gatling load tester and it has been wonderfully useful. Thank you devs for a great tool. 
I believe I've have found a bug. Please correct me if it's intended behavior.
When passing a NatsMessage into the NatsStreamingBuilder, I think the following line 

https://github.com/Logimethods/nats-connector-gatling/blob/47697efe93f3810d743ee1f4d7510207ed596f65/src/main/scala/com/logimethods/connector/gatling/to_nats/NatsStreamingAction.scala#L91

is causing messages to be published to the wrong subject. If the subject is named "testSubject1" it will publish to "testSubject1testSubject1".
The work around I'm using is to have the getSubject() method return an empty string. This has corrected the issue for me. 

Thank you

**Comment by laugimethods** [comment]
Hi,

I didn't touch that code for some time now... So, I don't remember the details of it.
My code might be wrong, but I would like to be sure before making any change to that line.

To help me to figure the issue, could you share your Gatling configuration, or better your complete project?

Best regards,
Laurent

**Comment by laugimethods** [comment]
Actually, it is not a bug. That line allows the combination of a "main" subject + a "sub-subject" per message.

See 
https://github.com/Logimethods/smart-meter/blob/master/dockerfile-app_inject/user-files/simulations/nats/NatsInjection.scala#L37
in conjunction with 
https://github.com/Logimethods/smart-meter/blob/master/dockerfile-app_inject/src/main/scala/com/logimethods/smartmeter/generate/ValueProvider.scala#L94

So, if you don't want the subject "testSubject1" being duplicated, you have to provide it juste once (in the protocol or in the message).

Does that answer your concern?

**Comment by DSwift510** [comment]
Much obliged, it definitely does. Thank you for expanding my understanding.
